name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type check
      run: npm run type-check
      
    - name: Run linter
      run: npm run lint
    
    - name: Build application
      run: npm run build
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Start application
      run: |
        npm run dev &
        npx wait-on http://localhost:3000
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Run load tests
      run: npm run test:load
      
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Check for environment variable exposure
      run: |
        echo "Checking for potential environment variable exposure..."
        if grep -r "NEXT_PUBLIC_.*_KEY\|NEXT_PUBLIC_.*_SECRET" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" .; then
          echo "❌ Found potential secret exposure in NEXT_PUBLIC_ variables"
          exit 1
        else
          echo "✅ No secret exposure found in NEXT_PUBLIC_ variables"
        fi

  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli@0.12.x
      
    - name: Start application
      run: |
        npm start &
        npx wait-on http://localhost:3000
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        
    - name: Run Lighthouse CI
      run: |
        lhci collect --url=http://localhost:3000 --url=http://localhost:3000/about
        lhci assert --config.assertions.performance=0.9 --config.assertions.accessibility=0.95 --config.assertions.best-practices=0.9 --config.assertions.seo=0.95